"use client";

import Navegation from "./components/navegation";
import Footer from "./containers/footer";
import "./globals.css";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className="bg-neutral-900">
        <Navegation />

        {children}
        <Footer />
      </body>
    </html>
  );
}
